name: Deploy to Stage

on:
  workflow_dispatch:

jobs:
  debug:
    name: Debugging information
    runs-on: ubuntu-latest
    steps:
      - name: Print debugging information
        run: |
          echo "Workflow run ID: ${{ github.run_id }}"
          echo "Workflow run number: ${{ github.run_number }}"
          echo "Event type: ${{ github.event_name }}"
          echo "Ref type: ${{ github.ref_type }}"
          echo "Ref name: ${{ github.ref_name }}"
          echo "Actor: ${{ github.actor }}"
          echo "Repository: ${{ github.repository }}"
          echo "Head commit: ${{ github.event.head_commit.id }}"
          echo "Head commit message: ${{ github.event.head_commit.message }}"
          echo "Head commit author: ${{ github.event.head_commit.author.name }}"
          echo "Head commit timestamp: ${{ github.event.head_commit.timestamp }}"
          echo "Head commit URL: ${{ github.event.head_commit.url }}"
          echo "Head commit message: ${{ github.event.head_commit.message }}"

  deploy:
    name: Deploy release to staging
    runs-on: ubuntu-latest
    steps:
      - name: Notify deployment success
        run: echo "Deployment to staging was successful!"
