name: Deploy to Stage

on:
  workflow_run:
    workflows: ["Test and build"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy release to staging
    if: ${{ github.ref_type == 'tag' }}
    runs-on: ubuntu-latest
    steps:
      - name: Notify deployment success
        run: echo "Deployment to staging was successful!"
