name: Deploy to Stage

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the environment to deployment"
        required: true
        type: choice
        options:
          - development
          - staging
          - production

jobs:
  debug:
    name: Debugging information
    runs-on: ubuntu-latest
    steps:
      - name: Print debugging information
        run: |
          echo "Workflow run ID: ${{ github.run_id }}"
          echo "Workflow run number: ${{ github.run_number }}"
          echo "Event type: ${{ github.event_name }}"
          echo "Ref type: ${{ github.ref_type }}"
          echo "Ref name: ${{ github.ref_name }}"
          echo "Actor: ${{ github.actor }}"
          echo "Repository: ${{ github.repository }}"
          echo "Environment: ${{ github.event.inputs.environment }}"

  deploy:
    name: Deploy release to staging
    runs-on: ubuntu-latest
    steps:
      - name: Notify deployment success
        run: echo "Deployment to staging was successful!"
