name: Test and build

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Do our tests
    runs-on: ubuntu-latest
    steps:
      - name: Test step
        run: echo "Running tests..."

      - name: Triggering build on tag
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh workflow run deploy-to-stage.yml --ref ${{ github.ref_name }}
