name: Test and build

on:
  push:
    tags:
      - "*"

jobs:
  build-tag:
    name: Do our tests
    runs-on: ubuntu-latest
    steps:
      - name: Test step
        run: echo "Running tests..."

  deploy-staging:
    name: Deploy minor tag to staging
    runs-on: ubuntu-latest
    needs: build-tag
    if: startsWith(github.ref, 'refs/tags/v') && endsWith(github.ref, '.0')
    steps:
      - name: Install GitHub CLI
        run: |
          curl -sS https://webi.sh/gh | sh
          source ~/.config/envman/PATH.env

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Triggering deployment workflow
        if: startsWith(github.ref, 'refs/tags/v') && endsWith(github.ref, '.0')
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow run deployment-tag.yml \
            --ref ${{ github.ref_name }} \
            --field environment=staging
