name: Test and build

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Do our tests
    runs-on: ubuntu-latest
    steps:
      - name: Test step
        run: echo "Running tests..."

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Triggering build on tag
        if: startsWith(github.ref, 'refs/tags/v') && endsWith(github.ref, '.0')
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh workflow run deploy-to-stage.yml --ref ${{ github.ref_name }}
