on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

name: release-please postprocess

jobs:
  postprocess:
    if: startsWith(github.head_ref, 'release-please--branches--')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Run custom script
        run: |
          npm run changelog:public

      - name: Commit file to release PR
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add test.txt
          git commit -m "chore: add generated file to release PR" || echo "No changes to commit"
          git push origin HEAD:${{ github.head_ref }}
