name: Trigger Release PR Creation

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  trigger-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Config git user
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create empty commit
        run: |
          git commit --allow-empty -m "chore: trigger release"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: release-trigger-branch
          delete-branch: true
          title: "chore: trigger release"
          body: "Automated PR to trigger release-please pull request creation."
