name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          target-branch: ${{ github.ref_name }}
          manifest-file: ".release-please/release-please-manifest.json"
          config-file: ".release-please/release-please-config.json"

  public-changelog:
    needs: release-please
    runs-on: ubuntu-latest
    if: needs.release-please.outputs.prs_created
    steps:
      - name: Branch name
        run: |
          echo "release_created: ${{ needs.release.outputs.prs_created }}"
          echo "PR: ${{ fromJSON(needs.release.outputs.pr) }}"
          echo "headBranchName: ${{ fromJSON(needs.release.outputs.pr).headBranchName }}"

      - name: Checkout release branch
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.release.outputs.pr.headBranchName }}

      - name: Generate public changelog
        run: |
          npm run changelog:public

      - name: Commit file to release PR
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add CHANGELOG_PUBLIC.md
          git commit -m "chore: generate public changelog" || echo "No changes to commit"
          git push origin HEAD:${{ fromJSON(needs.release-please.outputs.pr).headBranchName }}
