name: Release Please Hotfix

on:
  push:
    branches:
      - hotfix/**

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      pr: ${{ steps.release.outputs.pr }}
      prs_created: ${{ steps.release.outputs.prs_created }}
    steps:
      - name: Release please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          target-branch: ${{ github.ref_name }}
          manifest-file: ".release-please/release-please-manifest.json"
          config-file: ".release-please/release-please-config-hotfix.json"
