name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          target-branch: ${{ github.ref_name }}
          manifest-file: ".release-please/release-please-manifest.json"
          config-file: ".release-please/release-please-config.json"

      - name: Branch name
        run: |
          echo "release_created: ${{ steps.release.outputs.release_created }}"
          echo "PR: ${{ steps.release.outputs.pr }}"
          echo "version: ${{ steps.release.outputs.version }}"

      - name: Checkout release branch
        if: steps.release.outputs.prs_created
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.release.outputs.pr.headBranchName }}

      - name: Generate public changelog
        run: |
          npm run changelog:public

      - name: Commit file to release PR
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add CHANGELOG_PUBLIC.md
          git commit -m "chore: generate public changelog" || echo "No changes to commit"
          git push origin HEAD:${{ steps.release.outputs.pr.headBranchName }}
