name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      pr: ${{ steps.release.outputs.pr }}
      prs_created: ${{ steps.release.outputs.prs_created }}
    steps:
      - name: Release please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          target-branch: ${{ github.ref_name }}
          manifest-file: ".release-please/release-please-manifest.json"
          config-file: ".release-please/release-please-config.json"

  public-changelog:
    needs: release-please
    runs-on: ubuntu-latest
    if: needs.release-please.outputs.prs_created
    steps:
      - name: Checkout release branch
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.release.outputs.pr.headBranchName }}

      - name: Github actions bot user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Generate public changelog
        run: |
          npm run changelog:public

      - name: Commit file to release PR
        run: |
          git add CHANGELOG_PUBLIC.md
          git commit -m "chore: generate public changelog" || echo "No changes to commit"
          git fetch origin
          git push origin
